### ISSUE TITLE
appendData这个方法只在Version 2.0 吗

### ISSUE THREAD

**Issue by wangmiaoduan** [apache/incubator-echarts#11431]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by wangmiaoduan** [comment]
myChart.appendData({
   seriesIndex: 0,
   data: data
});
使用分片加载时，引用echarts.js Version 2.0 不会报错
其他版本都会提示myChart.appendData is not a function

**Comment by deqingli** [comment]
This interface was added after version 4.0.0 so it doesn't work in version 2.0.0

**Comment by wangmiaoduan** [comment]
thanks it have already been solved  use version 4.0.0
